### ISSUE TITLE
Move across mailboxes

### ISSUE THREAD

**Issue by jonschumacher** [daumling/tiny-imap-filter#1]
Hi,

I have the same problem of not being able to use imapfilter with my hoster. For me, an important feature of imapfilter is the ability to move mails between mailboxes. As far as I can see it, this is currently not possible with tiny-imap-filter. Is this correct?

Cheers
Jonas

**Comment by daumling** [comment]
Hi Jonas,

Unfortunately, this piece of PHP is only able to move mails from the inbox to other mailboxes. Feel free to extend the code, though.

Regards, Michael
