### ISSUE TITLE
One bug and one update due to php 7.2 changes

### ISSUE THREAD

**Issue by yet-another-steve** [daumling/tiny-imap-filter#2]
Line 96 change:
sendError('Cannot read imapfilter.ini');
to:
sendErrors('Cannot read imapfilter.ini');

Line 69 second argument no longer optional since php 7.2 so change:
$arr = parse_str($_SERVER['QUERY_STRING']);
to:
parse_str($_SERVER['QUERY_STRING'], $arr);

**Comment by daumling** [comment]
Got it, thank you!
